name: "HTML to PDF action"
description: "Converts HTML file to PDF."
author: "lukaszlapaj@interia.pl"
inputs:
  htmlFile:
    description: "html file path"
    required: true

  outputFile:
    description: "output file path"
    required: true

  pdfOptions:
    description: |
      PDF options as described here:
      https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagepdfoptions -
      Needs to be in JSON format, e.g. `{"format": "A4", "pageRanges": "1"}`
    required: false
    default: "{}"

runs:
  using: "docker"
  image: "ghcr.io/marcinmolenda/html-to-pdf-action:sha256-ad43acf05d7f7d50147bd4835d726f7ec6b79e4e58448109ea601c8e1f9fc47c.sig"

branding:
  color: "blue"
  icon: "file"
